# Netlify configuration for a Nuxt 3 application
[build]
  command = "yarn run generate"
  functions = "netlify/functions"
  publish = "dist" # Updated to the correct directory

# Redirects for Single Page Applications
# Uncomment the following if you need to handle routing via Netlify redirects
# This is useful if you're building a SPA or using client-side routing.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Optional settings for Netlify Dev
[dev]
  command = "yarn dev" # Assuming yarn dev is the command to start your Nuxt app
  port = 3000 # Default Nuxt development port
  publish = ".nuxt/dist" # Should match the publish directory in the build settings

# Additional settings can be added as needed
